namespace HeboTech.ATLib.Numbering
{
    internal class CountryCode
    {
        public CountryCode(int code, string country)
        {
            Code = code;
            Country = country;
            CodeAsString = code.ToString();
        }

        public int Code { get; }
        public string CodeAsString { get; }
        public string Country { get; }

        public override string ToString()
        {
            return $"{Code} ({Country})";
        }
    }

    internal static class CountryCodes
    {
        public static CountryCode[] Items = new CountryCode[207]
        {
            new CountryCode(1,"United States/Canada/Caribbean nations"),
            new CountryCode(7,"Russia/Kazakhstan"),
            new CountryCode(20,"Egypt"),
            new CountryCode(27,"South Africa"),
            new CountryCode(30,"Greece"),
            new CountryCode(31,"Netherlands"),
            new CountryCode(32,"Belgium"),
            new CountryCode(33,"France"),
            new CountryCode(34,"Spain"),
            new CountryCode(36,"Hungary"),
            new CountryCode(39,"Italy"),
            new CountryCode(40,"Romania"),
            new CountryCode(41,"Switzerland"),
            new CountryCode(43,"Austria"),
            new CountryCode(44,"United Kingdom"),
            new CountryCode(45,"Denmark"),
            new CountryCode(46,"Sweden"),
            new CountryCode(47,"Norway"),
            new CountryCode(48,"Poland"),
            new CountryCode(49,"Germany"),
            new CountryCode(51,"Peru"),
            new CountryCode(52,"Mexico"),
            new CountryCode(53,"Cuba"),
            new CountryCode(54,"Argentina"),
            new CountryCode(55,"Brazil"),
            new CountryCode(56,"Chile"),
            new CountryCode(57,"Colombia"),
            new CountryCode(58,"Venezuela"),
            new CountryCode(60,"Malaysia"),
            new CountryCode(61,"Australia"),
            new CountryCode(62,"Indonesia"),
            new CountryCode(63,"Philippines"),
            new CountryCode(64,"New Zealand"),
            new CountryCode(65,"Singapore"),
            new CountryCode(66,"Thailand"),
            new CountryCode(81,"Japan"),
            new CountryCode(82,"South Korea"),
            new CountryCode(84,"Vietnam"),
            new CountryCode(86,"China"),
            new CountryCode(90,"Turkey"),
            new CountryCode(91,"India"),
            new CountryCode(92,"Pakistan"),
            new CountryCode(93,"Afghanistan"),
            new CountryCode(94,"Sri Lanka"),
            new CountryCode(95,"Myanmar"),
            new CountryCode(98,"Iran"),
            new CountryCode(211,"South Sudan"),
            new CountryCode(212,"Morocco/Western Sahara"),
            new CountryCode(213,"Algeria"),
            new CountryCode(216,"Tunisia"),
            new CountryCode(218,"Libya"),
            new CountryCode(220,"Gambia"),
            new CountryCode(221,"Senegal"),
            new CountryCode(222,"Mauritania"),
            new CountryCode(223,"Mali"),
            new CountryCode(224,"Guinea"),
            new CountryCode(225,"Ivory Coast"),
            new CountryCode(226,"Burkina Faso"),
            new CountryCode(227,"Niger"),
            new CountryCode(228,"Togo"),
            new CountryCode(229,"Benin"),
            new CountryCode(230,"Mauritius"),
            new CountryCode(231,"Liberia"),
            new CountryCode(232,"Sierra Leone"),
            new CountryCode(233,"Ghana"),
            new CountryCode(234,"Nigeria"),
            new CountryCode(235,"Chad"),
            new CountryCode(236,"Central African Republic"),
            new CountryCode(237,"Cameroon"),
            new CountryCode(238,"Cape Verde"),
            new CountryCode(239,"São Tomé and Príncipe"),
            new CountryCode(240,"Equatorial Guinea"),
            new CountryCode(241,"Gabon"),
            new CountryCode(242,"Republic of the Congo"),
            new CountryCode(243,"Democratic Republic of the Congo"),
            new CountryCode(244,"Angola"),
            new CountryCode(245,"Guinea-Bissau"),
            new CountryCode(246,"British Indian Ocean Territory"),
            new CountryCode(247,"Ascension Island"),
            new CountryCode(248,"Seychelles"),
            new CountryCode(249,"Sudan"),
            new CountryCode(250,"Rwanda"),
            new CountryCode(251,"Ethiopia"),
            new CountryCode(252,"Somalia"),
            new CountryCode(253,"Djibouti"),
            new CountryCode(254,"Kenya"),
            new CountryCode(255,"Tanzania"),
            new CountryCode(256,"Uganda"),
            new CountryCode(257,"Burundi"),
            new CountryCode(258,"Mozambique"),
            new CountryCode(260,"Zambia"),
            new CountryCode(261,"Madagascar"),
            new CountryCode(262,"Reunion/Mayotte"),
            new CountryCode(263,"Zimbabwe"),
            new CountryCode(264,"Namibia"),
            new CountryCode(265,"Malawi"),
            new CountryCode(266,"Lesotho"),
            new CountryCode(267,"Botswana"),
            new CountryCode(268,"Eswatini"),
            new CountryCode(269,"Comoros"),
            new CountryCode(290,"St. Helena"),
            new CountryCode(291,"Eritrea"),
            new CountryCode(297,"Aruba"),
            new CountryCode(298,"Faroe Islands"),
            new CountryCode(299,"Greenland"),
            new CountryCode(350,"Gibraltar"),
            new CountryCode(351,"Portugal"),
            new CountryCode(352,"Luxembourg"),
            new CountryCode(353,"Ireland"),
            new CountryCode(354,"Iceland"),
            new CountryCode(355,"Albania"),
            new CountryCode(356,"Malta"),
            new CountryCode(357,"Cyprus"),
            new CountryCode(358,"Finland"),
            new CountryCode(359,"Bulgaria"),
            new CountryCode(370,"Lithuania"),
            new CountryCode(371,"Latvia"),
            new CountryCode(372,"Estonia"),
            new CountryCode(373,"Moldova"),
            new CountryCode(374,"Armenia"),
            new CountryCode(375,"Belarus"),
            new CountryCode(376,"Andorra"),
            new CountryCode(377,"Monaco"),
            new CountryCode(378,"San Marino"),
            new CountryCode(379,"Vatican"),
            new CountryCode(380,"Ukraine"),
            new CountryCode(381,"Serbia"),
            new CountryCode(382,"Montenegro"),
            new CountryCode(383,"Kosovo"),
            new CountryCode(385,"Croatia"),
            new CountryCode(386,"Slovenia"),
            new CountryCode(387,"Bosnia and Herzegovina"),
            new CountryCode(389,"North Macedonia"),
            new CountryCode(420,"Czech Republic"),
            new CountryCode(421,"Slovakia"),
            new CountryCode(423,"Liechtenstein"),
            new CountryCode(500,"Falkland Islands"),
            new CountryCode(501,"Belize"),
            new CountryCode(502,"Guatemala"),
            new CountryCode(503,"El Salvador"),
            new CountryCode(504,"Honduras"),
            new CountryCode(505,"Nicaragua"),
            new CountryCode(506,"Costa Rica"),
            new CountryCode(507,"Panama"),
            new CountryCode(508,"Saint Pierre and Miquelon"),
            new CountryCode(509,"Haiti"),
            new CountryCode(590,"Guadeloupe/St. Barthélemy/St. Martin"),
            new CountryCode(591,"Bolivia"),
            new CountryCode(592,"Guyana"),
            new CountryCode(593,"Ecuador"),
            new CountryCode(594,"French Guiana"),
            new CountryCode(595,"Paraguay"),
            new CountryCode(596,"Martinique"),
            new CountryCode(597,"Suriname"),
            new CountryCode(598,"Uruguay"),
            new CountryCode(599,"Netherlands Antilles/Caribbean Netherlands"),
            new CountryCode(670,"East Timor"),
            new CountryCode(672,"Australian External Territories"),
            new CountryCode(673,"Brunei"),
            new CountryCode(674,"Nauru"),
            new CountryCode(675,"Papua New Guinea"),
            new CountryCode(676,"Tonga"),
            new CountryCode(677,"Solomon Islands"),
            new CountryCode(678,"Vanuatu"),
            new CountryCode(679,"Fiji"),
            new CountryCode(680,"Palau"),
            new CountryCode(681,"Wallis and Futuna"),
            new CountryCode(682,"Cook Islands"),
            new CountryCode(683,"Niue"),
            new CountryCode(685,"Samoa"),
            new CountryCode(686,"Kiribati"),
            new CountryCode(687,"New Caledonia"),
            new CountryCode(688,"Tuvalu"),
            new CountryCode(689,"French Polynesia"),
            new CountryCode(690,"Tokelau"),
            new CountryCode(691,"Micronesia"),
            new CountryCode(692,"Marshall Islands"),
            new CountryCode(850,"North Korea"),
            new CountryCode(852,"Hong Kong"),
            new CountryCode(853,"Macau"),
            new CountryCode(855,"Cambodia"),
            new CountryCode(856,"Laos"),
            new CountryCode(880,"Bangladesh"),
            new CountryCode(886,"Taiwan"),
            new CountryCode(960,"Maldives"),
            new CountryCode(961,"Lebanon"),
            new CountryCode(962,"Jordan"),
            new CountryCode(963,"Syria"),
            new CountryCode(964,"Iraq"),
            new CountryCode(965,"Kuwait"),
            new CountryCode(966,"Saudi Arabia"),
            new CountryCode(967,"Yemen"),
            new CountryCode(968,"Oman"),
            new CountryCode(970,"Palestine"),
            new CountryCode(971,"United Arab Emirates"),
            new CountryCode(972,"Israel"),
            new CountryCode(973,"Bahrain"),
            new CountryCode(974,"Qatar"),
            new CountryCode(975,"Bhutan"),
            new CountryCode(976,"Mongolia"),
            new CountryCode(977,"Nepal"),
            new CountryCode(992,"Tajikistan"),
            new CountryCode(993,"Turkmenistan"),
            new CountryCode(994,"Azerbaijan"),
            new CountryCode(995,"Georgia"),
            new CountryCode(996,"Kyrgyzstan"),
            new CountryCode(998,"Uzbekistan")
        };
    }
}
