using System.Collections.Generic;

namespace HeboTech.ATLib.Commands
{
    public static class Errors
    {
        public static readonly IDictionary<int, string> CME = new Dictionary<int, string>
        {
            { 0, "phone failure" },
            { 1, "no connection to phone" },
            { 2, "phone-adaptor link reserved" },
            { 3, "operation not allowed" },
            { 4, "operation not supported" },
            { 5, "PH-SIM PIN required" },
            { 6, "PH-FSIM PIN required" },
            { 7, "PH-FSIM PUK required" },
            { 10, "SIM not inserted" },
            { 11, "SIM PIN required" },
            { 12, "SIM PUK required" },
            { 13, "SIM failure" },
            { 14, "SIM busy" },
            { 15, "SIM wrong" },
            { 16, "incorrect password" },
            { 17, "SIM PIN2	 required" },
            { 18, "SIM PUK2	 required" },
            { 20, "memory full" },
            { 21, "invalid index" },
            { 22, "not found" },
            { 23, "memory failure" },
            { 24, "text string too long" },
            { 25, "invalid characters in text string" },
            { 26, "dial string too long" },
            { 27, "invalid characters in dial string" },
            { 30, "no network service" },
            { 31, "network timeout" },
            { 32, "network not allowed - emergency call only" },
            { 40, "network personalisation PIN required" },
            { 41, "network personalisation PUK required" },
            { 42, "network subset personalisation PIN required" },
            { 43, "network subset personalisation PUK required" },
            { 44, "service provider personalisation PIN required" },
            { 45, "service provider personalisation PUK required" },
            { 46, "corporate personalisation PIN required" },
            { 47, "corporate personalisation PUK required" },
            { 99, "resource limitation" },
            { 100, "unknown" },
            { 103, "Illegal MS" },
            { 106, "Illegal ME" },
            { 107, "GPRS services not allowed" },
            { 111, "PLMN not allowed" },
            { 112, "Location area not allowed" },
            { 113, "Roaming not allowed in this location area" },
            { 132, "service option not supported" },
            { 133, "requested service option not subscribed" },
            { 134, "service option temporarily out of order" },
            { 148, "unspecified GPRS error" },
            { 149, "PDP authentication failure" },
            { 150, "invalid mobile class" },
            { 160, "DNS resolve failed" },
            { 161, "Socket open failed" },
            { 171, "MMS task is busy now" },
            { 172, "The MMS data is oversize" },
            { 173, "The operation is overtime" },
            { 174, "There is no MMS receiver" },
            { 175, "The storage for address is full" },
            { 176, "Not find the address" },
            { 177, "The connection to network is failed" },
            { 178, "Failed to read push message" },
            { 179, "This is not a push message" },
            { 180, "gprs is not attached" },
            { 181, "tcpip stack is busy" },
            { 182, "The MMS storage is full" },
            { 183, "The box is empty" },
            { 184, "failed to save MMS" },
            { 185, "It is in edit mode" },
            { 186, "It is not in edit mode" },
            { 187, "No content in the buffer" },
            { 188, "Not find the file" },
            { 189, "Failed to receive MMS" },
            { 190, "Failed to read MMS" },
            { 191, "Not M-Notification.ind" },
            { 192, "The MMS inclosure is full" },
            { 193, "Unknown" },
            { 600, "No Error" },
            { 601, "Unrecognized Command" },
            { 602, "Return Value Error" },
            { 603, "Syntax Error" },
            { 604, "Unspecified Error" },
            { 605, "Data Transfer Already" },
            { 606, "Action Already" },
            { 607, "Not At Cmd" },
            { 608, "Multi Cmd too long" },
            { 609, "Abort Cops" },
            { 610, "No Call Disc" },
            { 611, "BT SAP Undefined" },
            { 612, "BT SAP Not Accessible" },
            { 613, "BT SAP Card Removed" },
            { 614, "AT Not Allowed By Customer" },
            { 753, "missing required cmd parameter" },
            { 754, "invalid SIM command" },
            { 755, "invalid File Id" },
            { 756, "missing required P1/2/3 parameter" },
            { 757, "invalid P1/2/3 parameter" },
            { 758, "missing required command data" },
            { 759, "invalid characters in command data" },
            { 765, "Invalid input value" },
            { 766, "Unsupported mode" },
            { 767, "Operation failed" },
            { 768, "Mux already running" },
            { 769, "Unable to get control" },
            { 770, "SIM network reject" },
            { 771, "Call setup in progress" },
            { 772, "SIM powered down" },
            { 773, "SIM file not present" },
            { 791, "Param count not enough" },
            { 792, "Param count beyond" },
            { 793, "Param value range beyond" },
            { 794, "Param type not match" },
            { 795, "Param format invalid" },
            { 796, "Get a null param" },
            { 797, "CFUN state is 0 or 4" }
        };

        public static readonly IDictionary<int, string> CMS = new Dictionary<int, string>
        {
            { 1, "Unassigned(unallocated) number" },
            { 3, "No route to destination" },
            { 6, "Channel unacceptable" },
            { 8, "Operator determined barring" },
            { 10, "Call barred" },
            { 11, "Reserved" },
            { 16, "Normal call clearing" },
            { 17, "User busy" },
            { 18, "No user responding" },
            { 19, "User alerting, no answer" },
            { 21, "Short message transfer rejected" },
            { 22, "Number changed" },
            { 25, "Pre-emption" },
            { 26, "Non-selected user clearing" },
            { 27, "Destination out of service" },
            { 28, "Invalid number format (incomplete number)" },
            { 29, "Facility rejected" },
            { 30, "Response to STATUS ENQUIRY" },
            { 32, "Normal, unspecified" },
            { 34, "No circuit/channel available" },
            { 38, "Network out of order" },
            { 41, "Temporary failure" },
            { 42, "Switching equipment Congestion" },
            { 43, "Access information discarded" },
            { 44, "Requested circuit/channel not available" },
            { 47, "Resources unavailable, unspecified" },
            { 49, "Quality of service unavailable" },
            { 50, "Requested facility not subscribed" },
            { 55, "Requested facility not subscribed" },
            { 57, "Bearer capability not authorized" },
            { 58, "Bearer capability not presently available" },
            { 63, "Service or option not available, unspecified" },
            { 65, "Bearer service not implemented" },
            { 68, "ACM equal or greater than ACM maximum" },
            { 69, "Requested facility not implemented" },
            { 70, "Only restricted digital information bearer capability is available" },
            { 79, "Service or option not implemented, unspecified" },
            { 81, "Invalid transaction identifier value" },
            { 87, "User not member of CUG" },
            { 88, "Incompatible destination" },
            { 91, "Invalid transit network selection" },
            { 95, "Semantically incorrect message" },
            { 96, "Invalid mandatory information" },
            { 97, "Message type non-existent or not implemented" },
            { 98, "Message type not compatible with protocol state" },
            { 99, "Information element non-existent or not implemented" },
            { 100, "Conditional information element error" },
            { 101, "Message not compatible with protocol" },
            { 102, "Recovery on timer expiry" },
            { 111, "Protocol error, unspecified" },
            { 127, "Interworking, unspecified" },
            { 128, "Telematic interworking not supported" },
            { 129, "Short message Type 0 not supported" },
            { 130, "Cannot replace short message" },
            { 143, "Unspecified TP-PID error" },
            { 144, "Data coding scheme (alphabet) not supported" },
            { 145, "Message class not supported" },
            { 159, "Unspecified TP-DCS error" },
            { 160, "Command cannot be acted" },
            { 161, "Command unsupported" },
            { 175, "Unspecified TP-Command error" },
            { 176, "TPDU not supported" },
            { 192, "SC busy" },
            { 193, "No SC subscription" },
            { 194, "SC system failure" },
            { 195, "Invalid SME address" },
            { 196, "Destination SME barred" },
            { 197, "SM Rejected-Duplicate SM" },
            { 198, "TP-VPF not supported" },
            { 199, "TP-VP not supported" },
            { 208, "SIM SMS storage full" },
            { 209, "No SMS storage capability in SIM" },
            { 210, "Error in MS" },
            { 211, "Memory Capacity Exceeded" },
            { 212, "SIM Application Toolkit Busy" },
            { 213, "SIM data download error" },
            { 224, "CP retry exceed" },
            { 225, "RP trim timeout" },
            { 226, "SMS connection broken" },
            { 255, "Unspecified error cause" },
            { 300, "ME failure" },
            { 301, "SMS reserved" },
            { 302, "operation not allowed" },
            { 303, "operation not supported" },
            { 304, "invalid PDU mode" },
            { 305, "invalid text mode" },
            { 310, "SIM not inserted" },
            { 311, "SIM pin necessary" },
            { 312, "PH SIM pin necessary" },
            { 313, "SIM failure" },
            { 314, "SIM busy" },
            { 315, "SIM wrong" },
            { 316, "SIM PUK required" },
            { 317, "SIM PIN2 required" },
            { 318, "SIM PUK2 required" },
            { 320, "memory failure" },
            { 321, "invalid memory index" },
            { 322, "memory full" },
            { 323, "invalid input parameter" },
            { 324, "invalid input format" },
            { 325, "invalid input value" },
            { 330, "SMSC address unknown" },
            { 331, "no network" },
            { 332, "network timeout" },
            { 340, "no cnma ack" },
            { 500, "Unknown" },
            { 512, "SMS no error" },
            { 513, "Message length exceeds maximum length" },
            { 514, "Invalid request parameters" },
            { 515, "ME storage failure" },
            { 516, "Invalid bearer service" },
            { 517, "Invalid service mode" },
            { 518, "Invalid storage type" },
            { 519, "Invalid message format" },
            { 520, "Too many MO concatenated messages" },
            { 521, "SMSAL not ready" },
            { 522, "SMSAL no more service" },
            { 523, "Not support TP-Status-Report & TP-Command in storage" },
            { 524, "Reserved MTI" },
            { 525, "No free entity in RL layer" },
            { 526, "The port number is already registerred" },
            { 527, "There is no free entity for port number" },
            { 528, "More Message to Send state error" },
            { 529, "MO SMS is not allow" },
            { 530, "GPRS is suspended" },
            { 531, "ME storage full" },
            { 532, "Doing SIM refresh" }
        };
    }
}
